version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  db:
    build: ./backend/db
    ports:
      - '27017:27017'
